services:
  - type: web
    name: simba-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/telegram_bot.py
    envVars:
      - key: KINOS_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    plan: free
